### ISSUE TITLE
Criar Dockerfile e docker-compose.yml

### ISSUE THREAD

**Issue by Edufreitass** [carolinacampioni/fastfood-api#9]
Montar arquivos para subir app + banco PostgreSQL.

**Comment by Edufreitass** [comment]
🐳 Dockerfile (exemplo, não testado)

- Instalar dependências
- Compilar o TypeScript
- Rodar a versão buildada

```Dockerfile
# Etapa 1: Build da aplicação
FROM node:20-alpine AS build

# Diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# Instala dependências (sem devDependencies)
RUN npm install --legacy-peer-deps

# Copia o restante do código
COPY . .

# Compila o TypeScript
RUN npm run build

# Etapa 2: Imagem final para produção
FROM node:20-alpine

WORKDIR /app

# Apenas as dependências de produção
COPY package*.json ./
RUN npm install --only=production --legacy-peer-deps

# Copia o build gerado
COPY --from=build /app/dist ./dist

# Variáveis de ambiente
ENV NODE_ENV=production
ENV PORT=3000

# Expondo a porta
EXPOSE 3000

# Comando de inicialização
CMD ["node", "dist/server.js"]
```

**Comment by Edufreitass** [comment]
🐳 Docker Compose (exemplo, não testado)

```yaml
version: "3.8"

services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: fastfood_user
      POSTGRES_PASSWORD: fastfood_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://fastfood_user:fastfood_pass@database:5432/fastfood
    command: ["npm", "run", "start:prod"]
    restart: unless-stopped
    volumes:
      - .:/app

volumes:
  postgres_data:
```
